/**
 * TCL AI Integration Layer
 * TypeScript-AI Cognitive Layer para Skill.IA
 * 
 * Este módulo maneja la comunicación con los agentes de IA para:
 * - Generación dinámica de preguntas adaptativas
 * - Análisis de respuestas del usuario
 * - Generación de diagnóstico personalizado
 */

import Groq from "groq-sdk";

// ============================================
// TIPOS Y INTERFACES
// ============================================

export interface UserProfile {
  userId?: string;
  name?: string;
  sector?: string;
  experience?: string;
  aspiration?: string;
  initialEnglishLevel?: string;
}

export interface QuestionOption {
  id: string;
  text: string;
  value: number;
}

export interface Question {
  id: string;
  text: string;
  type: 'multiple-choice' | 'confidence-scale' | 'practical';
  category: 'technical' | 'soft-skills' | 'english';
  options?: QuestionOption[];
  metadata?: {
    difficulty?: 'easy' | 'medium' | 'hard';
    adaptiveContext?: string;
  };
}

export interface Answer {
  questionId: string;
  answer: string;
  value: number;
  timestamp: Date;
}

export interface DiagnosticResult {
  category: string;
  score: number;
  level: 'Básico' | 'Intermedio' | 'Avanzado';
  feedback: string;
  recommendations?: string[];
}

export interface AgentContext {
  userProfile: UserProfile;
  answeredQuestions: Answer[];
  currentProgress: number;
  detectedPatterns?: {
    learningStyle?: 'visual' | 'auditory' | 'kinesthetic' | 'reflective';
    confidenceLevel?: number;
    performanceTrend?: 'improving' | 'stable' | 'declining';
  };
}

// ============================================
// INTERFACES DE ROADMAP
// ============================================

export interface Resource {
  title: string;
  url: string;
  type: 'article' | 'video' | 'course' | 'exercise';
}

export interface Milestone {
  id: string;
  title: string;
  description: string;
  status: 'pending' | 'in-progress' | 'completed';
  progress: number;
  estimatedTime: string;
  difficulty: 'Básico' | 'Intermedio' | 'Avanzado';
  category: 'Technical' | 'Soft Skills' | 'English';
  objectives: string[];
  resources: Resource[];
  completedDate?: Date;
  aiGenerated?: boolean;
}

export interface RoadmapData {
  userId: string;
  milestones: Milestone[];
  overallProgress: number;
  generatedDate: Date;
  lastUpdated: Date;
}

// ============================================
// CONFIGURACIÓN DE AGENTES
// ============================================

export interface LLMConfig {
  provider: 'openai' | 'anthropic' | 'groq' | 'google';
  model: string;
  apiKey?: string;
  endpoint?: string;
}

export interface AgentConfig {
  questionGenerator: LLMConfig;
  responseAnalyzer: LLMConfig;
  diagnosticGenerator: LLMConfig;
}

// ============================================
// SERVICIO PRINCIPAL DE IA
// ============================================

export class DiagnosticAIService {
  private config: AgentConfig;
  private context: AgentContext;
  private groqClient: Groq | null = null;
  
  constructor(config: AgentConfig, userProfile: UserProfile) {
    this.config = config;
    this.context = {
      userProfile,
      answeredQuestions: [],
      currentProgress: 0,
    };

    // Inicializar cliente Groq si está configurado
    try {
      const apiKey = import.meta.env.PUBLIC_GROQ_API_KEY;
      if (apiKey && config.questionGenerator.provider === 'groq') {
        this.groqClient = new Groq({
          apiKey: apiKey,
          dangerouslyAllowBrowser: true // Necesario para uso en el navegador
        });
        console.log('✅ Groq client initialized successfully');
      } else {
        console.warn('⚠️ Groq API key not found. Set PUBLIC_GROQ_API_KEY in .env file');
      }
    } catch (error) {
      console.warn('❌ Groq client initialization failed, will use fallback:', error);
    }
  }

  /**
   * Genera la siguiente pregunta basada en el contexto actual
   */
  async generateNextQuestion(): Promise<Question> {
    const prompt = this.buildQuestionPrompt();
    
    console.log('🤖 Generating question...', {
      hasGroqClient: !!this.groqClient,
      questionNumber: this.context.answeredQuestions.length + 1
    });
    
    // Intentar generar con Groq
    if (this.groqClient) {
      try {
        console.log('📡 Calling Groq API...');
        const question = await this.generateQuestionWithGroq(prompt);
        if (question) {
          console.log('✅ Question generated by Groq:', question.text);
          return question;
        }
      } catch (error) {
        console.error('❌ Error generating question with Groq:', error);
        console.log('⚠️ Falling back to mock generation...');
      }
    } else {
      console.warn('⚠️ Groq client not available, using mock generation');
    }
    
    // Fallback: usar generación mock
    console.log('🔄 Using mock question generation');
    return this.mockQuestionGeneration();
  }

  /**
   * Genera una pregunta usando Groq API
   */
  private async generateQuestionWithGroq(prompt: string): Promise<Question | null> {
    if (!this.groqClient) return null;

    try {
      console.log('📤 Sending prompt to Groq...');
      
      const completion = await this.groqClient.chat.completions.create({
        messages: [
          {
            role: "system",
            content: `Eres un experto en evaluación de habilidades profesionales. Genera preguntas adaptativas para diagnosticar competencias técnicas, soft skills y nivel de inglés.

IMPORTANTE: Responde ÚNICAMENTE con un objeto JSON válido, sin texto adicional antes o después. El formato debe ser exactamente:

{
  "id": "string único",
  "text": "texto de la pregunta",
  "type": "multiple-choice" o "confidence-scale",
  "category": "technical" o "soft-skills" o "english",
  "options": [
    {"id": "opt-1", "text": "texto opción 1", "value": 5},
    {"id": "opt-2", "text": "texto opción 2", "value": 4},
    {"id": "opt-3", "text": "texto opción 3", "value": 3},
    {"id": "opt-4", "text": "texto opción 4", "value": 2}
  ],
  "metadata": {
    "difficulty": "easy" o "medium" o "hard"
  }
}

Las opciones deben tener values de 5 (mejor) a 1 (peor).`
          },
          {
            role: "user",
            content: prompt
          }
        ],
        model: "llama-3.3-70b-versatile", // Modelo actualizado
        temperature: 0.7,
        max_tokens: 1024,
        response_format: { type: "json_object" }
      });

      console.log('📥 Groq response received');

      const content = completion.choices[0]?.message?.content;
      if (!content) {
        console.error('❌ No content in Groq response');
        throw new Error('No content in Groq response');
      }

      console.log('📄 Parsing JSON response...');
      const questionData = JSON.parse(content);
      
      // Validar estructura de la respuesta
      if (!questionData.id || !questionData.text || !questionData.type || !questionData.category) {
        console.error('❌ Invalid question structure:', questionData);
        throw new Error('Invalid question structure from Groq');
      }

      // Asegurar que tenga opciones
      if (!questionData.options || !Array.isArray(questionData.options) || questionData.options.length === 0) {
        console.warn('⚠️ No options in response, generating defaults');
        // Generar opciones por defecto según el tipo
        questionData.options = questionData.type === 'confidence-scale' 
          ? this.getConfidenceOptions()
          : this.getMultipleChoiceOptions();
      }

      console.log('✨ Question validated successfully');
      return questionData as Question;

    } catch (error) {
      console.error('💥 Error in generateQuestionWithGroq:', error);
      return null;
    }
  }

  /**
   * Analiza la respuesta del usuario
   */
  async analyzeAnswer(answer: Answer): Promise<void> {
    this.context.answeredQuestions.push(answer);
    this.context.currentProgress = this.calculateProgress();
    
    // TODO: Implementar análisis con LLM
    const analysisPrompt = this.buildAnalysisPrompt(answer);
    console.log('Analysis Prompt:', analysisPrompt);
    
    // Detectar patrones
    this.detectLearningPatterns();
  }

  /**
   * Genera el diagnóstico completo
   */
  async generateDiagnostic(): Promise<DiagnosticResult[]> {
    // TODO: Implementar con LLM real
    const diagnosticPrompt = this.buildDiagnosticPrompt();
    console.log('Diagnostic Generation Prompt:', diagnosticPrompt);
    
    return this.mockDiagnosticGeneration();
  }

  /**
   * Actualiza el contexto del usuario
   */
  updateContext(updates: Partial<AgentContext>): void {
    this.context = { ...this.context, ...updates };
  }

  /**
   * Obtiene el contexto actual
   */
  getContext(): AgentContext {
    return { ...this.context };
  }

  // ============================================
  // MÉTODOS PRIVADOS - GENERACIÓN DE PROMPTS
  // ============================================

  private buildQuestionPrompt(): string {
    const { userProfile, answeredQuestions, detectedPatterns } = this.context;
    
    return `
You are an adaptive professional skills assessment AI. Generate the next question based on:

User Profile:
- Sector: ${userProfile.sector || 'Not specified'}
- Experience: ${userProfile.experience || 'Not specified'}
- Aspiration: ${userProfile.aspiration || 'Not specified'}

Answered Questions: ${answeredQuestions.length}
${answeredQuestions.map(a => `Q${a.questionId}: Value ${a.value}/5`).join('\n')}

Detected Patterns:
- Learning Style: ${detectedPatterns?.learningStyle || 'Unknown'}
- Confidence Level: ${detectedPatterns?.confidenceLevel || 'N/A'}
- Performance Trend: ${detectedPatterns?.performanceTrend || 'N/A'}

Instructions:
- Generate a question that adapts to the user's responses
- If previous answers show high competence, increase difficulty
- If previous answers show struggles, simplify and reinforce basics
- Balance technical, soft skills, and English assessment
- Return JSON format with: id, text, type, category, options

Generate the next adaptive question:
    `.trim();
  }

  private buildAnalysisPrompt(answer: Answer): string {
    return `
Analyze this user's answer in context:

Question ID: ${answer.questionId}
Answer: ${answer.answer}
Value: ${answer.value}/5

Previous Performance:
${this.context.answeredQuestions.slice(0, -1).map(a => `${a.questionId}: ${a.value}/5`).join('\n')}

Provide insights on:
1. User's competency level
2. Confidence vs. actual performance
3. Recommended next difficulty level
    `.trim();
  }

  private buildDiagnosticPrompt(): string {
    const answers = this.context.answeredQuestions;
    
    return `
Generate a comprehensive professional skills diagnostic based on these answers:

Total Questions: ${answers.length}

Technical Skills Answers:
${this.filterByCategory('technical').map(a => `${a.questionId}: ${a.value}/5`).join('\n')}

Soft Skills Answers:
${this.filterByCategory('soft-skills').map(a => `${a.questionId}: ${a.value}/5`).join('\n')}

English Proficiency Answers:
${this.filterByCategory('english').map(a => `${a.questionId}: ${a.value}/5`).join('\n')}

For each category, provide:
1. Overall score (0-100)
2. Level classification (Básico, Intermedio, Avanzado)
3. Personalized feedback
4. 2-3 specific recommendations

Return results in JSON format.
    `.trim();
  }

  // ============================================
  // MÉTODOS PRIVADOS - ANÁLISIS Y LÓGICA
  // ============================================

  private calculateProgress(): number {
    const totalExpected = 10; // Ajustable
    return Math.min(100, (this.context.answeredQuestions.length / totalExpected) * 100);
  }

  private detectLearningPatterns(): void {
    const answers = this.context.answeredQuestions;
    if (answers.length < 3) return;

    // Detectar tendencia de performance
    const recent = answers.slice(-3);
    const avgRecent = recent.reduce((sum, a) => sum + a.value, 0) / recent.length;
    const avgPrevious = answers.slice(0, -3).reduce((sum, a) => sum + a.value, 0) / (answers.length - 3);

    if (avgRecent > avgPrevious + 0.5) {
      this.context.detectedPatterns = {
        ...this.context.detectedPatterns,
        performanceTrend: 'improving',
      };
    } else if (avgRecent < avgPrevious - 0.5) {
      this.context.detectedPatterns = {
        ...this.context.detectedPatterns,
        performanceTrend: 'declining',
      };
    } else {
      this.context.detectedPatterns = {
        ...this.context.detectedPatterns,
        performanceTrend: 'stable',
      };
    }

    // Detectar nivel de confianza
    const avgConfidence = answers.reduce((sum, a) => sum + a.value, 0) / answers.length;
    this.context.detectedPatterns = {
      ...this.context.detectedPatterns,
      confidenceLevel: avgConfidence,
    };
  }

  private filterByCategory(category: string): Answer[] {
    // En implementación real, esto filtraría por categoría real de la pregunta
    // Por ahora retorna muestra
    return this.context.answeredQuestions.filter((_, idx) => {
      if (category === 'technical') return idx % 3 === 0;
      if (category === 'soft-skills') return idx % 3 === 1;
      if (category === 'english') return idx % 3 === 2;
      return false;
    });
  }

  // ============================================
  // MÉTODOS MOCK (Temporales)
  // ============================================

  private mockQuestionGeneration(): Question {
    const categories: Array<'technical' | 'soft-skills' | 'english'> = ['technical', 'soft-skills', 'english'];
    const types: Array<'multiple-choice' | 'confidence-scale'> = ['multiple-choice', 'confidence-scale'];
    
    const category = categories[this.context.answeredQuestions.length % 3];
    const type = this.context.answeredQuestions.length % 2 === 0 ? 'confidence-scale' : 'multiple-choice';

    return {
      id: `ai-q-${Date.now()}`,
      text: `[IA Generated] Pregunta adaptativa para ${category}`,
      type,
      category,
      options: type === 'confidence-scale' ? this.getConfidenceOptions() : this.getMultipleChoiceOptions(),
      metadata: {
        difficulty: this.calculateNextDifficulty(),
        adaptiveContext: 'Generated based on previous answers',
      },
    };
  }

  private calculateNextDifficulty(): 'easy' | 'medium' | 'hard' {
    const recent = this.context.answeredQuestions.slice(-3);
    if (recent.length === 0) return 'medium';

    const avgRecent = recent.reduce((sum, a) => sum + a.value, 0) / recent.length;
    
    if (avgRecent >= 4) return 'hard';
    if (avgRecent >= 2.5) return 'medium';
    return 'easy';
  }

  private getConfidenceOptions(): QuestionOption[] {
    return [
      { id: 'always', text: 'Siempre', value: 5 },
      { id: 'often', text: 'A menudo', value: 4 },
      { id: 'sometimes', text: 'A veces', value: 3 },
      { id: 'rarely', text: 'Raramente', value: 2 },
      { id: 'never', text: 'Nunca', value: 1 },
    ];
  }

  private getMultipleChoiceOptions(): QuestionOption[] {
    return [
      { id: 'opt-1', text: 'Opción avanzada', value: 5 },
      { id: 'opt-2', text: 'Opción intermedia', value: 3 },
      { id: 'opt-3', text: 'Opción básica', value: 2 },
      { id: 'opt-4', text: 'Sin experiencia', value: 1 },
    ];
  }

  private mockDiagnosticGeneration(): DiagnosticResult[] {
    const categories = [
      { name: 'Habilidades Técnicas', key: 'technical' },
      { name: 'Habilidades Blandas', key: 'soft-skills' },
      { name: 'Dominio de Inglés', key: 'english' },
    ];

    return categories.map(cat => {
      const categoryAnswers = this.filterByCategory(cat.key);
      const avgScore = categoryAnswers.length > 0
        ? (categoryAnswers.reduce((sum, a) => sum + a.value, 0) / categoryAnswers.length / 5) * 100
        : 50;

      let level: 'Básico' | 'Intermedio' | 'Avanzado' = 'Básico';
      if (avgScore >= 70) level = 'Avanzado';
      else if (avgScore >= 40) level = 'Intermedio';

      return {
        category: cat.name,
        score: Math.round(avgScore),
        level,
        feedback: `[IA] Retroalimentación personalizada para ${cat.name}`,
        recommendations: [
          `Recomendación 1 basada en tu nivel ${level}`,
          `Recomendación 2 según tu perfil`,
        ],
      };
    });
  }
}

// ============================================
// UTILIDADES DE EXPORTACIÓN
// ============================================

/**
 * Crea una instancia del servicio de diagnóstico con configuración por defecto
 */
export function createDiagnosticService(userProfile: UserProfile): DiagnosticAIService {
  const defaultConfig: AgentConfig = {
    questionGenerator: {
      provider: 'groq', // Cambiado a Groq
      model: 'llama-3.3-70b-versatile', // Modelo actualizado
    },
    responseAnalyzer: {
      provider: 'groq',
      model: 'llama-3.3-70b-versatile',
    },
    diagnosticGenerator: {
      provider: 'groq',
      model: 'llama-3.3-70b-versatile',
    },
  };

  return new DiagnosticAIService(defaultConfig, userProfile);
}

/**
 * Hook de Vue composable para usar el servicio de IA
 */
export function useDiagnosticAI(userProfile: UserProfile) {
  const service = createDiagnosticService(userProfile);
  
  return {
    generateNextQuestion: () => service.generateNextQuestion(),
    analyzeAnswer: (answer: Answer) => service.analyzeAnswer(answer),
    generateDiagnostic: () => service.generateDiagnostic(),
    getContext: () => service.getContext(),
    updateContext: (updates: Partial<AgentContext>) => service.updateContext(updates),
  };
}

// ============================================
// SERVICIO DE ROADMAP CON IA
// ============================================

export class RoadmapAIService {
  private config: AgentConfig;
  private userProfile: UserProfile;
  private diagnosticResults: DiagnosticResult[];

  constructor(config: AgentConfig, userProfile: UserProfile, diagnosticResults: DiagnosticResult[]) {
    this.config = config;
    this.userProfile = userProfile;
    this.diagnosticResults = diagnosticResults;
  }

  /**
   * Genera un roadmap personalizado basado en el diagnóstico
   */
  async generateRoadmap(): Promise<RoadmapData> {
    // TODO: Implementar llamada real al LLM
    const prompt = this.buildRoadmapPrompt();
    console.log('Roadmap Generation Prompt:', prompt);

    // Mock generation
    return this.mockRoadmapGeneration();
  }

  /**
   * Actualiza el roadmap basándose en el progreso del usuario
   */
  async updateRoadmap(currentRoadmap: RoadmapData, completedMilestones: string[]): Promise<RoadmapData> {
    // TODO: Implementar actualización con IA
    const prompt = this.buildUpdatePrompt(currentRoadmap, completedMilestones);
    console.log('Roadmap Update Prompt:', prompt);

    return this.mockRoadmapUpdate(currentRoadmap, completedMilestones);
  }

  /**
   * Genera nuevo milestone adaptativo basado en progreso
   */
  async generateAdaptiveMilestone(progress: RoadmapData): Promise<Milestone> {
    // TODO: Implementar con LLM
    const prompt = this.buildAdaptiveMilestonePrompt(progress);
    console.log('Adaptive Milestone Prompt:', prompt);

    return this.mockAdaptiveMilestone();
  }

  // ============================================
  // MÉTODOS PRIVADOS - GENERACIÓN DE PROMPTS
  // ============================================

  private buildRoadmapPrompt(): string {
    return `
Generate a personalized professional development roadmap based on:

User Profile:
- Name: ${this.userProfile.name || 'Unknown'}
- Sector: ${this.userProfile.sector || 'Not specified'}
- Experience: ${this.userProfile.experience || 'Not specified'}
- Aspiration: ${this.userProfile.aspiration || 'Not specified'}
- English Level: ${this.userProfile.initialEnglishLevel || 'Not specified'}

Diagnostic Results:
${this.diagnosticResults.map(r => `
  ${r.category}: ${r.score}/100 - Level: ${r.level}
  Feedback: ${r.feedback}
`).join('\n')}

Instructions:
1. Generate 5-7 milestones that progressively build skills
2. Start with gaps identified in the diagnostic
3. Order milestones from foundational to advanced
4. Include technical, soft skills, and English milestones
5. Each milestone should have:
   - Clear title and description
   - 3-4 learning objectives
   - 3-5 recommended resources
   - Estimated time to complete
   - Difficulty level

Return JSON format with complete roadmap structure.
    `.trim();
  }

  private buildUpdatePrompt(roadmap: RoadmapData, completed: string[]): string {
    return `
Update this roadmap based on user progress:

Completed Milestones: ${completed.length}
${completed.map(id => {
  const milestone = roadmap.milestones.find(m => m.id === id);
  return milestone ? `- ${milestone.title} (${milestone.category})` : id;
}).join('\n')}

Current Milestones:
${roadmap.milestones.map(m => `${m.title}: ${m.status}`).join('\n')}

Instructions:
1. Analyze what the user has completed
2. Identify new skill gaps or opportunities
3. Suggest 1-2 new milestones that build on progress
4. Adjust difficulty of pending milestones if needed
5. Ensure logical skill progression

Return updated roadmap in JSON format.
    `.trim();
  }

  private buildAdaptiveMilestonePrompt(progress: RoadmapData): string {
    const completedMilestones = progress.milestones.filter(m => m.status === 'completed');
    
    return `
Generate a new adaptive milestone based on user's progress:

Completed Milestones:
${completedMilestones.map(m => `- ${m.title} (${m.category}, ${m.difficulty})`).join('\n')}

Overall Progress: ${progress.overallProgress}%

User Profile:
- Aspiration: ${this.userProfile.aspiration || 'Not specified'}
- Experience: ${this.userProfile.experience || 'Not specified'}

Instructions:
1. Analyze the user's learning trajectory
2. Identify the next logical skill to develop
3. Consider their professional aspiration
4. Create a challenging but achievable milestone
5. Include specific, actionable objectives

Return single milestone in JSON format.
    `.trim();
  }

  // ============================================
  // MÉTODOS MOCK (Temporales)
  // ============================================

  private mockRoadmapGeneration(): RoadmapData {
    const baseMilestones: Milestone[] = [
      {
        id: 'rm-1',
        title: 'Fundamentos de SQL',
        description: 'Aprende consultas básicas y manejo de bases de datos relacionales.',
        status: 'pending',
        progress: 0,
        estimatedTime: '2 semanas',
        difficulty: 'Básico',
        category: 'Technical',
        objectives: [
          'Dominar SELECT, WHERE, JOIN',
          'Crear y modificar tablas',
          'Entender normalización de datos'
        ],
        resources: [
          { title: 'SQL para Principiantes', url: '#', type: 'course' },
          { title: 'Guía de SQL Básico', url: '#', type: 'article' },
          { title: 'Práctica con SQLZoo', url: '#', type: 'exercise' }
        ],
        aiGenerated: true
      },
      {
        id: 'rm-2',
        title: 'Comunicación Efectiva en Equipos',
        description: 'Desarrolla habilidades de comunicación clara y asertiva.',
        status: 'pending',
        progress: 0,
        estimatedTime: '3 semanas',
        difficulty: 'Intermedio',
        category: 'Soft Skills',
        objectives: [
          'Practicar escucha activa',
          'Dar y recibir feedback constructivo',
          'Presentar ideas de forma clara'
        ],
        resources: [
          { title: 'Comunicación Asertiva', url: '#', type: 'video' },
          { title: 'Curso de Soft Skills', url: '#', type: 'course' }
        ],
        aiGenerated: true
      },
      {
        id: 'rm-3',
        title: 'Inglés Técnico Básico',
        description: 'Vocabulario y comprensión de documentación técnica en inglés.',
        status: 'pending',
        progress: 0,
        estimatedTime: '4 semanas',
        difficulty: 'Básico',
        category: 'English',
        objectives: [
          'Leer documentación técnica',
          'Escribir emails profesionales',
          'Participar en reuniones básicas'
        ],
        resources: [
          { title: 'Technical English Course', url: '#', type: 'course' },
          { title: 'IT Vocabulary Guide', url: '#', type: 'article' }
        ],
        aiGenerated: true
      }
    ];

    return {
      userId: this.userProfile.userId || 'unknown',
      milestones: baseMilestones,
      overallProgress: 0,
      generatedDate: new Date(),
      lastUpdated: new Date()
    };
  }

  private mockRoadmapUpdate(current: RoadmapData, completed: string[]): RoadmapData {
    // Simular actualización: agregar un nuevo milestone si se completó uno
    const newMilestone: Milestone = {
      id: `rm-new-${Date.now()}`,
      title: '[IA] Módulo Adaptativo Avanzado',
      description: 'Nuevo desafío basado en tu progreso reciente.',
      status: 'pending',
      progress: 0,
      estimatedTime: '3 semanas',
      difficulty: 'Avanzado',
      category: 'Technical',
      objectives: [
        'Objetivo adaptativo 1',
        'Objetivo adaptativo 2',
        'Objetivo adaptativo 3'
      ],
      resources: [
        { title: 'Recurso Avanzado', url: '#', type: 'course' }
      ],
      aiGenerated: true
    };

    return {
      ...current,
      milestones: [...current.milestones, newMilestone],
      lastUpdated: new Date(),
      overallProgress: (completed.length / (current.milestones.length + 1)) * 100
    };
  }

  private mockAdaptiveMilestone(): Milestone {
    return {
      id: `adaptive-${Date.now()}`,
      title: '[IA] Proyecto de Integración',
      description: 'Aplica todos tus conocimientos en un proyecto real.',
      status: 'pending',
      progress: 0,
      estimatedTime: '4 semanas',
      difficulty: 'Avanzado',
      category: 'Technical',
      objectives: [
        'Integrar múltiples tecnologías',
        'Demostrar dominio completo',
        'Crear solución escalable'
      ],
      resources: [
        { title: 'Proyecto Capstone', url: '#', type: 'exercise' },
        { title: 'Guía de Implementación', url: '#', type: 'article' }
      ],
      aiGenerated: true
    };
  }
}

// ============================================
// UTILIDADES PARA ROADMAP
// ============================================

/**
 * Crea una instancia del servicio de roadmap
 */
export function createRoadmapService(
  userProfile: UserProfile,
  diagnosticResults: DiagnosticResult[]
): RoadmapAIService {
  const defaultConfig: AgentConfig = {
    questionGenerator: {
      provider: 'openai',
      model: 'gpt-4',
    },
    responseAnalyzer: {
      provider: 'anthropic',
      model: 'claude-3-sonnet',
    },
    diagnosticGenerator: {
      provider: 'openai',
      model: 'gpt-4',
    },
  };

  return new RoadmapAIService(defaultConfig, userProfile, diagnosticResults);
}

/**
 * Hook composable para usar el servicio de Roadmap
 */
export function useRoadmapAI(userProfile: UserProfile, diagnosticResults: DiagnosticResult[]) {
  const service = createRoadmapService(userProfile, diagnosticResults);

  return {
    generateRoadmap: () => service.generateRoadmap(),
    updateRoadmap: (roadmap: RoadmapData, completed: string[]) => 
      service.updateRoadmap(roadmap, completed),
    generateAdaptiveMilestone: (progress: RoadmapData) => 
      service.generateAdaptiveMilestone(progress),
  };
}

